baseurl = "https://rekadata.net"
relativeurls = true
title = "Dr Reka Solymosi"
theme = "pulp"
#canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
googleAnalytics = "{UA-143850780-1}"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

[taxonomies]
  series = "series"

[params]
    author = "Dr Reka Solymosi"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Reka is a Senior Lecturer in Quantitative Methods at the University of Manchester’s Department of Criminology. 
        She is a member of the Software Sustainability Institute and an Honorary Lecturer at University College London. 
        Reka’s research uses innovative data collection methods such as crowdsourced perceptions, real-time surveys 
        using apps, and physiological measures, to study issues like crime, victimisation, and urban safety. 
        She enjoys using quantitative and computational techniques and spatial data analysis to explore topics 
        such as fear of crime, public engagement, and the impact of policy decisions on public behaviour. 
        Her work spans various domains, including crime prevention, transport safety, violence against women, fear of crime, and guardianship. 
        She has published extensively in leading journals such as The British Journal of Criminology and Policing and Society, and contributed to books 
        like The Oxford Handbook of Environmental Criminology as well as written textbooks and teaching material on 
        using R in quantitative and spatial crime analysis. Reka is also dedicated to improving data literacy in the social sciences 
        to support both research and policy development.
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]



[[menu.main]]
    identifier = "research"
    name = "Research" #If display text link, cancel comment out
    pre = "<i class='fa fa-flask fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/research/"
    weight = 1

[[menu.main]]
    identifier = "teaching"
    name = "Teaching" #If display text link, cancel comment out
    pre = "<i class='fa fa-chalkboard-teacher fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/teaching/"
    weight = 2
    

[[menu.main]]
    identifier = "blog"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" 
    url = "/blog/"
    weight = 3
    
[[menu.main]]
    identifier = "talks"
    name = "Talks" #If display text link, cancel comment out
    pre = "<i class='fas fa-volume-up'></i>" 
    url = "/talks/"
    weight = 4
    
[[menu.main]]
    identifier = "CV"
    name = "CV" #If display text link, cancel comment out
    pre = "<i class='fa fa-id-card fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/cv/cv.pdf"
    weight = 5    
    

[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/r_solymosi"
    weight = 6

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    pre = "<i class='fa fa-newspaper fa-lg'></i>"
    url = "https://scholar.google.com/citations?user=IXexMmEAAAAJ&hl=en"
    weight = 7

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/maczokni"
    weight = 8

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:reka.solymosi@manchester.ac.uk"
    weight = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
